[project]
name = "litellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AreebaZafarChohan", email = "areebazafar715@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.0",
]

